### ISSUE TITLE
Automated test suite

### ISSUE THREAD

**Issue by JohannesBuchner** [joshspeagle/dynesty#112]
Related to #10, it would inspire confidence to have a automated test suite that is run often.

Unit tests (testing individual components, mocking dependencies if needed) and Integration tests (testing everything together) are common ways to do this.

This can be nicely automated by services like Travis-CI (or more recently Circle CI), which run the test suite with various OSs, python versions and upstream dependencies (e.g., numpy/scipy versions).

I implemented this in my github repos for nway, pymultinest: the .travis.yml files, setup.py/cfg test and tests/ directories should get you started. Already just testing that a trivial run doesn't give an Exception or returns results within some range is useful.

**Comment by JohannesBuchner** [comment]
Thinking more advanced, one could imagine running a (slower) test suite on some example problems to test the behaviour of algorithms (see, e.g., testsuite in https://github.com/JohannesBuchner/UltraNest/,  some results here: https://johannesbuchner.github.io/UltraNest/testsuite/). But "failures" may not be failures of the implementations, but just properties of the algorithms. So that kind of testing would be a different topic I think.

**Comment by joshspeagle** [comment]
Agreed. I'll get to this when I get #10 set up.
