### ISSUE TITLE
terminalout error

### ISSUE THREAD

**Issue by joshspeagle** [joshspeagle/dynesty#114]
After upgrading to the latest dynesty version which includes this update, I get nothing at PyCharm's output tab. Debian Testing + Python 3.7 + PyCharm 2018.3 community edition

_Originally posted by @bek0s in https://github.com/joshspeagle/dynesty/pull/110#issuecomment-466785493_

**Comment by bek0s** [comment]
Hi,

I will just provide some additional information in case it helps. If I open a terminal tab from PyCharm and run my software from there, I do not have this problem. This problem happens only when I run PyCharm from the "Run" menu. The weird thing now is that when this happens, I can still get dynesty's output if I focus on PyCharm's output tab and press the Enter key. However, that output won't keep updating, so I essentially need to keep the Enter key pressed. Finally, I can get rid of this problem completely by going to PyCharm's Run/Debug configuration and enabling the `Emulate terminal in output console` option. I am not quite sure what all these mean, maybe it is a PyCharm bug or some misconfiguration on my system. Nevertheless, if I just use the PyPI version of dynesty everything works just fine.

Thanks!

**Comment by joshspeagle** [comment]
Bizarre. I'll check to see if there's any weird overwriting happening that might be causing this, but otherwise I'll plan to close this in a few days if nothing obvious turns up.
