### ISSUE TITLE
Merging results - `samples_n AttributeError`

### ISSUE THREAD

**Issue by GregoryAshton** [joshspeagle/dynesty#118]
Hi Josh.

The new work looks really great! I was playing with the `merge_runs` feature and have come across a potential bug.

I ran several jobs (using the standard `NestedSampler`, i.e. not-dynamic) and dumped the `Result` object to a pickle. Then loaded in the dumped objects and put them in a list. When I fed this into `utils.merge_runs` I received an `AttributeError` for `samples_n`  sourced from [this line](https://github.com/joshspeagle/dynesty/blob/master/dynesty/utils.py#L912). 

I hacked around it by using the way it is calculated [earlier on in the code](https://github.com/joshspeagle/dynesty/blob/master/dynesty/utils.py#L406). Is this a reasonable fix?

**Comment by joshspeagle** [comment]
Oh dear, that does look like a bug. Your fix looks correct to me, so I'll see if I can patch it in at some point in the near future.

**Comment by GregoryAshton** [comment]
I can push a MR if you like?

**Comment by joshspeagle** [comment]
That'd be great! Happy to accept it.
