### ISSUE TITLE
exception in propose_live

### ISSUE THREAD

**Issue by segasai** [joshspeagle/dynesty#126]
Hi, 

I'm seeing an exception while sampling a very difficult (almost degenerate) posterior. 
See backtrace below, together with local variables printed.
As far as I understand the error it is caused by propose_live() selecting one live point and finding 
it is not inside any ellipsoid, then triggering update, and still finding that the point is outside ellipsoid. This in turns leads to randint(0) call, which raises an exception.

```
ipdb> bt                                                                                                    
  /home/skoposov/pyenv36/lib/python3.6/site-packages/IPython/utils/py3compat.py(188)execfile()
    186     with open(fname, 'rb') as f:
    187         compiler = compiler or compile
--> 188         exec(compiler(f.read(), fname, 'exec'), glob, loc)
    189 
    190 # Refactor print statements in doctests.

  /home/skoposov/science/hvs_x/ejection_mass.py(190)<module>()
    186     import multiprocessing as mp
    187     pool = mp.Pool(24)
    188     samp = dynesty.DynamicNestedSampler(func, cubeprior, 9, pool=pool, queue_size=100,
    189                                         nlive=1000, sample='slice')
--> 190     samp.run_nested()

  /home/skoposov/pyenv36/lib/python3.6/site-packages/dynesty/dynamicsampler.py(1500)run_nested()
   1498                                                maxiter=maxiter_init,
   1499                                                logl_max=logl_max_init,
-> 1500                                                live_points=live_points):
   1501                 (worst, ustar, vstar, loglstar, logvol,
   1502                  logwt, logz, logzvar, h, nc, worst_it,

  /home/skoposov/pyenv36/lib/python3.6/site-packages/dynesty/dynamicsampler.py(740)sample_initial()
    738             for it, results in enumerate(self.sampler.sample(maxiter=maxiter,
    739                                          save_samples=False,
--> 740                                          maxcall=maxcall, dlogz=dlogz)):
    741                 # Grab results.
    742                 (worst, ustar, vstar, loglstar, logvol, logwt,

  /home/skoposov/pyenv36/lib/python3.6/site-packages/dynesty/sampler.py(702)sample()
    700             # `logl > loglstar` using the bounding distribution and sampling
    701             # method from our sampler.
--> 702             u, v, logl, nc = self._new_point(loglstar_new, logvol)
    703             ncall += nc
    704             self.ncall += nc

  /home/skoposov/pyenv36/lib/python3.6/site-packages/dynesty/sampler.py(331)_new_point()
    329         while True:
    330             # Get the next point from the queue
--> 331             u, v, logl, nc, blob = self._get_point_value(loglstar)
    332             ncall += nc
    333 

  /home/skoposov/pyenv36/lib/python3.6/site-packages/dynesty/sampler.py(315)_get_point_value()
    313         # If the queue is empty, refill it.
    314         if self.nqueue <= 0:
--> 315             self._fill_queue(loglstar)
    316 
    317         # Grab the earliest entry.

  /home/skoposov/pyenv36/lib/python3.6/site-packages/dynesty/sampler.py(284)_fill_queue()
    282             if self._beyond_unit_bound(loglstar):
    283                 # Propose points using the provided sampling/bounding options.
--> 284                 point, axes = self.propose_point()
    285                 evolve_point = self.evolve_point
    286             else:

> /home/skoposov/pyenv36/lib/python3.6/site-packages/dynesty/nestedsamplers.py(622)propose_live()
    620 
    621         # Pick a random ellipsoid that encompasses `u`.
--> 622         ell_idx = ell_idxs[self.rstate.randint(nidx)]
    623 
    624         # Choose axes.

  /home/skoposov/science/hvs_x/mtrand.pyx(992)mtrand.RandomState.randint()

ipdb> print (locals())                                                                                      
{'bound': <dynesty.bounding.MultiEllipsoid object at 0x7fb01c1ed358>, 'pointvol': 0.001996007984031936, 'expected_vol': 0.998003992015968, 'nidx': 0, 'ell_idxs': array([], dtype=int64), 'u': array([0.22019067, 0.28467831, 0.35547402, 0.96339442, 0.73116038,
       0.01936248, 0.09082527, 0.29700396, 0.02150998]), 'i': 373, 'self': <dynesty.nestedsamplers.MultiEllipsoidSampler object at 0x7fb0e66186d8>}
```

I don't quite understand all the details of the algorithm to figure out what is the appropriate fix for the problem.

Thanks.

**Comment by joshspeagle** [comment]
> As far as I understand the error it is caused by propose_live() selecting one live point and finding
it is not inside any ellipsoid, then triggering update, and still finding that the point is outside ellipsoid. This in turns leads to randint(0) call, which raises an exception.

Yes, I agree that appears to be what's happening.

> while sampling a very difficult (almost degenerate) posterior.

My guess is what's happening is:
(1) During ellipsoid construction it finds that your points are degenerate and can't be inverted to construct the bounding ellipsoid.
(2) It then executes [this](https://github.com/joshspeagle/dynesty/blob/master/dynesty/bounding.py#L1202) in an attempt to regularize the ellipsoid until it's stable enough to invert.
(3) It then attempts to expand the ellipsoid to cover all the points used to construct it.

This *should* never fail; the fact that it is suggests some amount of numerical instability, something weird going on with the live points, or some other bug upstream (unstable distance computation, etc.).

My first recommendation with these types of things is always to try and de-correlate the parameters so they are not so degenerate and behave better, but that's not always an option. I should be able to find out how this is failing in particular if I had more information (like the `results` dictionary after adding in the final set of live points).

**Comment by segasai** [comment]
Unfortunately the run leading to the error took half a day on a couple of dozen CPUs, and since then I closed the pdb/ipython session. I will see if I can detect the error again and give more info.

I also couldn't really decorrelate the parameters in my problem...

**Comment by joshspeagle** [comment]
> I also couldn't really decorrelate the parameters in my problem...

Yea, that's no problem. I'm aware it's not always possible :).

> I will see if I can detect the error again and give more info.

Great. If you do encounter it again please send me everything you can so I can try to debug it. I've been trying to squash various forms of this error for almost as long as `dynesty` has existed as a package with varying degrees of success.

**Comment by segasai** [comment]
I have got the same failure now, and I have the pdb session running.
The backtrace is the same as shown above 

I wonder if  potentially the problem is the very low expected_vol ? 
```
 ipdb> print (locals())                                                          
{'bound': <dynesty.bounding.MultiEllipsoid object at 0x7f6ad0440d68>, 'pointvol': 4.208462379204299e-138, 'expected_vol': 2.1042311896021495e-135, 'nidx': 0, 'ell_idxs': array([], dtype=int64), 'u': array([0.28466667, 0.38833878, 0.24295489, 0.50778797, 0.50969121,
       0.01753983, 0.04829411, 0.74833379, 0.19327246]), 'i': 429, 'self': <dynesty.nestedsamplers.MultiEllipsoidSampler object at 0x7f6d29f41a90>}
```
Please tell me what variables you need, I can pickle them. 
I also checked the live points distribution and I am certainly getting very correlated distribution with low eigen values

ipdb> scipy.linalg.eigh(np.cov(self.live_u.T))[0]                               
array([7.05746425e-15, 5.65868021e-14, 2.02954695e-09, 3.15941268e-09,
       7.20946372e-08, 1.09309116e-07, 3.55217347e-07, 5.44938975e-06,
       4.96063437e-02])

ipdb> np.diag(np.cov(self.live_u.T))                                            
array([8.99923531e-08, 1.27244953e-07, 1.17105282e-07, 6.69504766e-08,
       1.05027329e-07, 2.57920107e-06, 2.93028969e-06, 4.64341280e-02,
       3.17219109e-03])

I have now pickled 
dynesty.bounding.MultiEllipsoid and live_u, as I think they are keys to the problem.

**Comment by joshspeagle** [comment]
Great. If you could send the `live_u`, and `MultiEllipsoid` pickles to me, that'd be great. If you also have a copy of the `results` dictionary, that would help too.

**Comment by segasai** [comment]
I attach the zip with the live_u and MultiEllipsoide pkl's. 
Also I couldnt' find from which layer the stacktrace i can get the results dict...
[pkl.zip](https://github.com/joshspeagle/dynesty/files/3087849/pkl.zip)

**Comment by joshspeagle** [comment]
Great. I’ll try to take a look at this at some point in the ~upcoming week to see if I can figure out what’s going on.

**Comment by joshspeagle** [comment]
This is a lot later than a week (sorry...), but I did end up looking into this and completely forgot about responding. As far as I can tell, your initial suspicions are correct: this is an issue where the ellipsoid bounding totally blew up. *Why* it blew up is still a mystery to me, because even though the eigenvalues are small and the points are highly correlated, they *are* non-zero and so the ellipsoid should have been constructed just fine. Instead, the mean exists but the covariance is `nan` everywhere, which is a failure mode I have not encountered elsewhere (and regardless should be accounted for [here](https://github.com/joshspeagle/dynesty/blob/master/dynesty/bounding.py#L1458)). I'll leave this open for a bit in case there's been some development on this, but otherwise might close it if we don't make any progress.
