### ISSUE TITLE
saving state

### ISSUE THREAD

**Issue by jluastro** [joshspeagle/dynesty#127]
I have a couple of questions regarding state handling for especially long runs:

- Is there any way to save the state of the sampler to a file and then reload it and keep going? This could be in between calls to run_nested() or potential some kind of flushing mechanism every N calls or N iterations. 
- Is there someway to visualize what is happening in the fitter in real time? I know there is the print_function; but I want to see some plots on slower timescales than I want to see the printing (to make sure things are still running).

I included these in one issue as they are connected in terms of implementation. 

Thanks!
Jessica Lu

**Comment by joshspeagle** [comment]
Hey Jessica,

> Is there any way to save the state of the sampler to a file and then reload it and keep going? This could be in between calls to run_nested() or potential some kind of flushing mechanism every N calls or N iterations.

If you want to save the state of the sampler, just `pickle`-ing the whole thing should work.

> Is there someway to visualize what is happening in the fitter in real time? I know there is the print_function; but I want to see some plots on slower timescales than I want to see the printing (to make sure things are still running).

`dynesty` has the ability to be run as a generator. I have an outline [in the docs](https://dynesty.readthedocs.io/en/latest/quickstart.html#running-externally) and one of the Jupyter notebook demos. This allows you to do things during the sampling such as making intermediate plots, dumping data to disk, etc. One such example is the implementation in [prospector](https://github.com/bd-j/prospector/blob/master/prospect/fitting/nested.py).

**Comment by joshspeagle** [comment]
Closing this.
