### ISSUE TITLE
Issue with new scipy versions (scipy>=1.3.0)

### ISSUE THREAD

**Issue by MNGuenther** [joshspeagle/dynesty#145]
Scipy's `logsumexp` function has been moved/renamed from version >=1.3.0 onwards, leading to dynesty failing with the following error:
`AttributeError: module 'scipy.misc' has no attribute 'logsumexp'`

**Comment by joshspeagle** [comment]
This should not be triggering in later versions -- I think every part of the code has a `try...except` statement that first attempts to import from `scipy.special` and then from `scipy.misc`. Could you flag exactly what version you are using and where this is popping up?

**Comment by MNGuenther** [comment]
Thanks Josh! I was using dynesty version 0.9.5.3. I have now updated to 0.9.7, that should solve the issue. Sorry for the false alarm, feel free to close this ticket!

**Comment by joshspeagle** [comment]
Okay. Let me know if you run into any other weird things -- there seems to be a problem with stalled runs that I'm looking into, so if anything else that seems suspicious/affects your runs pops up please continue to raise issues! :)
