### ISSUE TITLE
Refactor samplers to incorporate separate bounding/sampling methods

### ISSUE THREAD

**Issue by joshspeagle** [joshspeagle/dynesty#15]
As I've gone along and started adding new sampling methods, I've noticed that no sampler can really function completely independently of some method for bounding the distribution -- they all require some tunable proposal distributions, especially to deal with multiple modes. As such, it makes more and more sense to allow for a sampler to bound with one method and propose with another. A list of these methods (so far) are below.

Bounding:
- none (global)
- single ellipsoid (global)
- multiple ellipsoids (global)
- radfriends (per point?)
- supfriends (per point?)

Sampling:
- uniform (global)
- random walk (from point)
- repeated slicing (from point)
- random trajectory (from point)

I should change how the samplers work to allow users to specify both options via some `bound` and `sampling` keywords. This also solves a several other problems: you want to propose at different modes based on their volume, you want your proposal tuned to where you are (to some extent) based on the distribution of live points, etc.

**Comment by bd-j** [comment]
ooh I like this!
