### ISSUE TITLE
Slow converging

### ISSUE THREAD

**Issue by minaskar** [joshspeagle/dynesty#169]
I'm experimenting with the crash-course example from the docs in high dimensions and I noticed that it takes too long to converge.

In particular, for the 25-dimensional correlated normal, it takes almost 45million likelihood calls or about 25minutes in a high-end i7 CPU. Is this expected?

**Comment by joshspeagle** [comment]
Yes, this is expected. As discussed in the docs, the majority of the runtime in high-dimensional cases is almost-always dominated by integrating over the prior. In that case, we are integrating out at 10-sigma (roughly speaking). Assuming most of the Gaussian is contained within 3-sigma (ish), this means the prior is larger than the likelihood by a factor of (10/3)^D, leading to runtimes that scale as ~D * log(10/3). You can see this firsthand in the 25-D correlated normal [demo](https://github.com/joshspeagle/dynesty/blob/master/demos/Examples%20--%2025-D%20Correlated%20Normal.ipynb), which is also included in the documentation.

Hope this helps.

**Comment by minaskar** [comment]
There's another thing too. Dynasty does not recover the "true" covariance of the target distribution for highly correlated cases.

You can reproduce this by sampling from a highly correlated 30-dimensional normal.
You can set the diagonal of the covariance to 1.0 and the non-diagonal elements to 0.95.

Dynasty systematically underestimates both variance and covariance in that case (i.e. estimated diagonal elements are 0.92 and non-diagonal are 0.87).
