### ISSUE TITLE
Converting samples to a different parameter set

### ISSUE THREAD

**Issue by ahallcosmo** [joshspeagle/dynesty#180]
Hi,

I have the results of a Nested Sampling run with a particular set of parameters. If I want to post-process the results to a different parameterisation (e.g., to plot the posterior of exp(x) rather than x), is it just a case of applying the appropriate transform to the samples? So for a 1D problem, with samples from the posterior of x, I could do something like results['samples'] = np.exp(results['samples']) to get a results class entirely equivalent to what I would have got by using exp(x) as a parameter in the sampling rather than x? Or are there any other metadata in the results class that would need to be modified too?

Best wishes,
Alex

**Comment by joshspeagle** [comment]
> I could do something like results['samples'] = np.exp(results['samples'])

Yes, that should work with no problems. No other data should need to be modified.

**Comment by ahallcosmo** [comment]
Thanks!
