### ISSUE TITLE
UserWarning during plotting question

### ISSUE THREAD

**Issue by avivajpeyi** [joshspeagle/dynesty#200]
What does the following warning mean? 
```
The number of iterations and samples differ by an amount that isn't the number of final live points.
```

Raised by 
```
dynesty/plotting.py:173: UserWarning: The number of iterations and samples differ by an amount that isn't the number of final live points. `mark_final_live` has been disabled
```

**Comment by joshspeagle** [comment]
By default, runplot tries to add a little dashed line to indicate where the sampling terminated and the final set of live points are “recycled” to augment the set of samples. It checks for this by just seeing whether the number of samples is equal to the number of iterations plus the final number of live points. If they differ (which can happen for a variety of reasons), then this feature is just disabled and this warning is thrown. Does that help?

**Comment by avivajpeyi** [comment]
Yes! Thank you :)
