### ISSUE TITLE
xrange -> range

### ISSUE THREAD

**Issue by bd-j** [joshspeagle/dynesty#21]
`xrange` only exists for python2.  However, the `concurrent.futures` package with `ThreadPoolExecutor` or `ProcessPoolExecutor` only exists in python3

**Comment by joshspeagle** [comment]
What's a better way to iterate through things then? There are a couple of `xrange(sys.maxiter)` options floating around to keep things iterators, and generating a list or array seems very wasteful. Does `range` do that in python3?

**Comment by bd-j** [comment]
yes, range in 3 acts like xrange in 2.

see here for compatible patterns
http://python-future.org/compatible_idioms.html

**Comment by joshspeagle** [comment]
Fantastic. I'll scour through and fix those tomorrow.
