### ISSUE TITLE
Reference for scaling behaviour of total number of steps N

### ISSUE THREAD

**Issue by mvsoom** [joshspeagle/dynesty#215]
First of all, thank you very much for this wonderful package!

From the [docs](https://dynesty.readthedocs.io/en/latest/overview.html?highlight=information#priors-in-nested-sampling):

> It can be shown/argued that the total number of steps N needed to integrate over the posterior roughly scales as: `$N \propto HK$`

Could you provide a reference for this? I couldn't find anything anywhere myself, including the dynesty paper.

**Comment by joshspeagle** [comment]
Ah yes, that's from the [original Skilling paper](https://projecteuclid.org/download/pdf_1/euclid.ba/1340370944), Section 8.

**Comment by mvsoom** [comment]
Thanks for the reply! Did you mean Section 7 [eq. (17)] instead of Section 8?

**Comment by joshspeagle** [comment]
Ah sorry! Yes -- Section 7.

**Comment by mvsoom** [comment]
Thanks again :)
