### ISSUE TITLE
Slice sampling scaling/updates

### ISSUE THREAD

**Issue by segasai** [joshspeagle/dynesty#260]
While debugging some issue with slice sampling 
I've encountered this reference 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4063214/
(as well as 2002.06212 ) which suggests that the slice sampling step should be scaled by 
2*nexpand/(nexpand+ncontract)

While the dynesty code 
https://github.com/joshspeagle/dynesty/blob/b3dbd52369a9b9172b20e76cb53ddd7f43bf9a1c/py/dynesty/nestedsamplers.py#L249
 scales by nexpand/(2 ncontract)

Is there any reason for the nonstandard scaling ?

**Comment by joshspeagle** [comment]
I hadn't done a ton of digging into scaling heuristics at the time that I chose that (apparently nonstandard) strategy, so there isn't too much reason behind it. Happy to change to the more commonly used approach if it looks like it performs better.

**Comment by segasai** [comment]
I've tried making a change and testing on Rosenbrock or Funnel distributions without an obvious improvement in number of evaluations. So lets keep things as they are unless there is a proof it's better.

**Comment by joshspeagle** [comment]
Should now be resolved as of #319.
