### ISSUE TITLE
Samples near the edge of the box

### ISSUE THREAD

**Issue by segasai** [joshspeagle/dynesty#261]
Over last few days I was trying to debug the issue in sampling slowing down to a crawl, and it was happening with all the samples sitting exactly at the edge of the cube (in u-space) and somehow that was breaking slice sampling. I remember multinest issues a warning in this case. That may be a good idea too. (i.e. if all live points sit within eps of 0 or 1 of the edge)

**Comment by joshspeagle** [comment]
Adding in warnings for this particular edge case (literally, hah) does sound like a good idea.
