### ISSUE TITLE
add_batch and multi-modal distributions

### ISSUE THREAD

**Issue by segasai** [joshspeagle/dynesty#327]
While looking at the ipynb notebook of the exponential wave problem ( #111)

 I ran it and discovered that by default we miss the second mode of the posterior (there are two modes due to permutations)  even with 500 live points. And that is not being recovered even by the dynamic run. 

```
import dynesty
import numpy as np
from dynesty import utils as dyutil

rstate = np.random.default_rng(1)
x = rstate.uniform(0, 2 * np.pi, size=100)
x.sort()

# define model
fa = 4.2 / 4
fb = 42 / 10
na = 0.8
nb = 0.3
pa = 0.1
pb = 2.4
sigma = 0.2

# generate noisy observations
ypred = np.exp(na * np.sin(x * fa + pa) + nb * np.sin(x * fb + pb))
y = rstate.normal(ypred, sigma)

def prior_transform(u):
    v = u * 100
    v[0] = u[0] * 4 - 2
    v[1] = u[1] * 4 - 2
    v[2] = (u[2] % 1.) * 2 * np.pi
    v[3] = u[3] * 4 - 2
    v[4] = u[4] * 4 - 2
    v[5] = (u[5] % 1.) * 2 * np.pi
    v[6] = u[6] * 2 - 2
    return v

def loglike(v):
    logna, logfa, pa, lognb, logfb, pb, logsigma = v
    na, fa, pa, nb, fb, pb, sigma = (10**logna, 10**logfa, pa, 10**lognb,
                                     10**logfb, pb, 10**logsigma)
    ypred = np.exp(na * np.sin(x * fa + pa) + nb * np.sin(x * fb + pb))
    residsq = (ypred - y)**2 / sigma**2
    loglike = -0.5 * np.sum(residsq + np.log(2 * np.pi * sigma**2))
    if not np.isfinite(loglike):
        loglike = -1e300
    return loglike

rstate = np.random.default_rng(5)
# sample
ndim = 7
nlive = 500
sampler = dynesty.DynamicNestedSampler(loglike,
                                       prior_transform,
                                       ndim,
                                       periodic=[2, 5],
                                       sample='rslice',
                                       nlive=nlive,
                                       rstate=rstate)
sampler.run_nested()
res = sampler.results
wht = np.exp(res.logwt - res.logz[-1])
chain = dyutil.resample_equal(res.samples, wht)
print('fraction in one mode', (chain[:, 1] < chain[:, 4]).sum() * 1. / len(chain))
```

This is obviously concerning, IMO, especially since the dynamic aspect of nested sapling doesnt' recover it. 
After that I just took and run add_batch for the logl range where the two modes are: 

```
sampler.add_batch(logl_bounds=(-50, 20),                  maxcall=1000000,
                  stop_val=0,                  dlogz=np.nan)
```

And even after one run  the second mode was recovered. 
Which lead me to think that the logic of allocating logl_bounds for add_batch is missing one key reason for more runs is the missing of posterior modes, (and again I am especially surprised that it could happen with 500 points and 2 equal width modes; AFAIU it happens because of stochastisticity of peak discovery, if one peak is discovered earlier than other one more points are allocated to it and after the second one is found, it's easily can loose all the live points) 

So while thinking about I also thought of a test problem of really large number of peaks and the behaviour of dynamic sampler vs manual  add_batch covering large range of logl.

This is an extreme version of eggbox with 900 posterior modes. 
```
(pyenv38) skoposov@milkyway:~/curwork/dynesty$ cat supermult.py
import dynesty
import numpy as np
from dynesty import utils as dyutil
import scipy.special

rstate = np.random.default_rng(1)

N = 30

xgrid, ygrid = np.mgrid[:N, :N]


def prior_transform(u):
    return u * N


def loglike(v):
    x, y = v
    s = 0.1
    logp = -0.5 * ((x - xgrid)**2 + (y - ygrid)**2) / s**2
    logp = scipy.special.logsumexp(logp)
    return logp


rstate = np.random.default_rng(4)

# sample
ndim = 2
nlive = 500
sampler = dynesty.DynamicNestedSampler(loglike,
                                       prior_transform,
                                       ndim,
                                       sample='rslice',
                                       nlive=nlive,
                                       rstate=rstate)
sampler.run_nested()
res = sampler.results
wht = np.exp(res.logwt - res.logz[-1])
chain = dyutil.resample_equal(res.samples, wht)
```

This is what you get  with the standard dynamic nested sampling (500 live points) (it runs for ~6 batches)

![Screenshot from 2021-09-04 23-21-01](https://user-images.githubusercontent.com/109513/132109335-dd0a9671-928d-4854-b435-7fcc4bfc3f03.png)
which is obviously not great

However if I now just run 100 times 
```
for i in range (100):
    sampler.add_batch(logl_bounds=(-50, -.1),                  maxcall=1000000,
                  stop_val=0,
                  dlogz=np.nan)

````
I get a really nice posterior

![Screenshot from 2021-09-04 23-25-43](https://user-images.githubusercontent.com/109513/132109386-c54ade90-96b9-4c6c-91ac-a5912beaa6d0.png)

which leads me to think that the default rule of allocating new dynamic runs can be improved.
I don't immediately have suggestions what it should be, but for example the issue is now that the default behaviour of 
add_batch() without loglbounds is to chose what's selected by the weight function, but it's clear that the weight_function is   suboptimal if the issue is the multimodality. 

(I understsand that I could in principle have several independent runs  and then merge them, but that obviously have disadvantages of not using previous bound info, plus there is IMO a point of being able to run dynamic nested sampling for longer to improve the results ,check convergence, like one does with regular MCMC)

**Comment by joshspeagle** [comment]
Agreed that for this case the general dynamic point allocation using the baseline run will tend to miss modes. There probably are modifications to make this more robust including expanding the logl_bounds, but not sure about the best way to implement them by default. One solution could involve some combination of padding and (essentially) forced restarts, along with modified stopping criteria that take some probability of missing modes of a certain size into account (rather than the current ones, which mostly track the posterior "noise" and/or evidence error).

**Comment by segasai** [comment]
> Agreed that for this case the general dynamic point allocation using the baseline run will tend to miss modes.

I think what was surprising is that you don't need 900 modes to be missed. Even if one has two equal  modes (although narrowish), there is a strong possibility of one being missed (even with 500 live points), and it's easy to just not realize it.

> There probably are modifications to make this more robust including expanding the logl_bounds, but not sure about the best way to implement them by default. One solution could involve some combination of padding and (essentially) forced restarts, along with modified stopping criteria that take some probability of missing modes of a certain size into account (rather than the current ones, which mostly track the posterior "noise" and/or evidence error).

I don't have a specific proposal yet, although being able to do add_batch() which would basically do a 'forced restart' would be helpful. 

If I had to guess the most likely point where the new runs need to be allocated due to possible multi-modality are the points where the volume start to shrink very rapidly, (or more precisely the logl growth slows down). 
I.e here is the example from the exponential wave fit 

This is logl vs fa (the frequency parameter where we loose the second mode)
![Screenshot from 2021-09-06 23-49-08](https://user-images.githubusercontent.com/109513/132264223-d8cfef15-e903-4582-95f9-f96b1a58cb73.png)

And here is the iteration vs logl 

![Screenshot from 2021-09-06 23-49-46](https://user-images.githubusercontent.com/109513/132264266-4e53cd91-1a65-46ab-9933-e484ee7cfe7c.png)

So I had to guess the inflection point correspond to change in topology and where we are more likely to loose modes and where it's potentially good to sample more. (a simple gaussian doesn't have any inflection point on the logvol vs logl plot)

**Comment by joshspeagle** [comment]
Right. It might be reasonable to add in an additional parameter that contributes to the weighting scheme based on the second derivative of the log-likelihood vs iteration curve that would encourage the sampler to revisit those locations "just in case". Do you think that could work?

**Comment by segasai** [comment]
I think, potentially it would work, but it probably requires quite a bit more thinking/testing ... I'm not confident enough in the inflection point theory to start putting that in, plus one would want some criteria when to stop...   
I would say an immediately actionable item is being able to do extra full runs. I'm wondering if run_nested() executed again should just do that. Or maybe we need to add some option to add_batch that say logl_bounds can be 'auto', 'entire' or list of two numbers, so we'd be able to make full runs when it is set to 'entire' and when set to 'auto' it would be current behaviour.

**Comment by joshspeagle** [comment]
The latter option seems like it would be easy to implement and reasonably effective, so it sounds like a good addition!
