### ISSUE TITLE
resample_equal corner-case

### ISSUE THREAD

**Issue by segasai** [joshspeagle/dynesty#336]
While running some large processing, I've hit this issue,
which unfortunately couldn't easily reproduce

```
  samples_equal = dyfunc.resample_equal(results.samples, weights)
  File "/home/skoposov/pyenv38/lib/python3.8/site-packages/dynesty/utils.py", line 366, in resample_equal
    if positions[i] < cumulative_sum[j]:
IndexError: index 4730 is out of bounds for axis 0 with size 4730
```
If i had to guess it has to do with loss of precision when doing sums/cumulative sums

**Comment by joshspeagle** [comment]
Oof, that looks like it's a numerical precision issue. Any ideas for how to avoid this edge case?

**Comment by segasai** [comment]
Not really. I need to catch in the act. I tried running with random inputs for many iterations and that didn't work.

**Comment by segasai** [comment]
As I expected the issue was a floating point accuracy issue. 

Here are the values of the last elements of positions and cumulative_sum arrays in the loop
```
In [36]: positions[-1]
Out[36]: 0.999999999182593
In [37]: cumulative_sum[-1]
Out[37]: 0.9999999981438245
```
Basically the issue is the last element of cumulative_sum not being 1. 
#351 solves the issue
