### ISSUE TITLE
merge_runs bug

### ISSUE THREAD

**Issue by segasai** [joshspeagle/dynesty#341]
While working on updating the notebooks https://github.com/joshspeagle/dynesty/tree/notebook_fixes 

The following test
```python 
import numpy as np
from numpy import linalg
from matplotlib import pyplot as plt
import dynesty
from dynesty import plotting as dyplot
from dynesty import utils as dyfunc

ndim = 3  # number of dimensions
C = np.identity(ndim)  # set covariance to identity matrix
C[C == 0] = 0.95  # set off-diagonal terms (strongly correlated)
Cinv = linalg.inv(C)  # precision matrix
lnorm = -0.5 * (np.log(2 * np.pi) * ndim + np.log(linalg.det(C))
                )  # ln(normalization)


# 3-D correlated multivariate normal log-likelihood
def loglikelihood(x):
    """Multivariate normal log-likelihood."""
    return -0.5 * np.dot(x, np.dot(Cinv, x)) + lnorm


# prior transform
def prior_transform(u):
    """Transforms our unit cube samples `u` to a flat prior between -10. and 10. in each variable."""
    return 10. * (2. * u - 1.)


rstate = np.random.default_rng(1)

nlive = 1000

lnz_truth = ndim * -np.log(2 * 10.)

# dynamic nested sampling
dsampler = dynesty.DynamicNestedSampler(
    loglikelihood,
    prior_transform,
    ndim,
    bound='single',
    sample='unif',
    rstate=rstate,
    #                                        nlive=nlive
)
maxiter = 12000
dsampler.run_nested(maxiter=maxiter, use_stop=False)
dres = dsampler.results

dres_list = dyfunc.unravel_run(dres)  # unravel run
dres_merge = dyfunc.merge_runs(dres_list)  # merge strands

# plotting merged results
fig, axes = dyplot.runplot(dres, color='red', mark_final_live=False)
fig, axes = dyplot.runplot(dres_merge,
                           color='blue',
                           fig=(fig, axes),
                           lnz_truth=lnz_truth,
                           lnz_error=False,
                           truth_color='black')
fig.tight_layout()
plt.show()

```
gives an incorrect result
![image](https://user-images.githubusercontent.com/109513/138319575-2ad0293f-10cc-47f3-8fea-08442f9e4806.png)

It seems to be caused by the commit 3ebd16bba83efac82e9b99615cecc19d5ad75bc1
I don't have the fix yet.

**Comment by segasai** [comment]
I think the underlying reason is weird and potentially incorrect behaviour of unravel(). 
https://github.com/joshspeagle/dynesty/blob/020daa0dae04aa12a314de5f30ab920ddfc615a9/py/dynesty/utils.py#L947

It returns an 'almost static' run results, but then it tries to also add 'samples_batch' and friends. 
I also do not quite follow whether the behaviour of unravel_ is correct if say the number of live points used in base run is different from base run. (because the stranding seems to be done by id) but maybe I'm missing something.

**Comment by segasai** [comment]
@joshspeagle Could you comment on this issue please when you have time. 
I wanted to address this before finishing stuff for the release (because this code is used in the notebooks)

**Comment by joshspeagle** [comment]
Oh jeez. I confirmed in previous notebooks that this did work, so this is something we definitely want to try and patch up. Theoretically, yes -- one can unravel a dynamic run and re-merge the results, although the previous way I did things led to incorrect calculations for some intermediate quantities post-merging. You just need to know the likelihood regions which each live point was sampled within, and so when you add a new live point in you just increase the count over the new likelihood bounds. This was one of the reason I kept the `logl_bounds` around for each new batch.

**Comment by segasai** [comment]
I think I am still convinced that unravel returns incorrect results for dynamic runs. here is the code (based on the test

```
import pickle
import numpy as np
import pytest
import dynesty
import dynesty.utils as dyutil

from utils import get_rstate
"""
Run a series of basic tests changing various things like
maxcall options and potentially other things
"""

nlive = 100

size = 10  # box size


def loglike(x):
    return -0.5 * np.sum(x**2)


def prior_transform(x):
    return (2 * x - 1) * size


def test_func():
    ndim = 2
    rstate = get_rstate()

    sampler = dynesty.DynamicNestedSampler(loglike,
                                           prior_transform,
                                           ndim,
                                           nlive=nlive,
                                           rstate=rstate)
    sampler.run_nested(maxbatch=2)
    return sampler
```
that runs two batches with default params. And now I plot  the samples_id vs logvol. 
after running test_func()

![image](https://user-images.githubusercontent.com/109513/142732086-a429e4ae-7161-4e4a-8ee9-55e98b1b8382.png)

You can see that some samples_id correspond to incomplete runs (coming from a batch with more live-points). I don't think that makes sense. 

Also IMO I can see the point of unravel_runs *only* if it is correct on its own, rather then it's  defining it as inverse of merge_runs (i.e merge_runs(unravel(X))==X) because unravel is not actually used anywhere.
