### ISSUE TITLE
Low iteration speed when likelihood is confined in small portion of prior

### ISSUE THREAD

**Issue by yaojian95** [joshspeagle/dynesty#343]
Hi, thanks for this nice tool! 
I'll try to explain my problem in a detailed way. 

I have a likelihood function involved with 2 parameter, _A0_ and _beta_ and I sample the likelihood with 

`dynesty.NestedSampler(my_loglike, my_prior, npara, nlive=400, bootstrap = 0)`

The prior for _A0_ is flexible while for _beta_ the best knowledge is -4 < _beta_ < -2. But in this case, dynesty samples with a very slow iteration speed (~1 it/s) for most of the time. And it take about 15 minutes before it can sample with a relatively faster speed and finally gives a correct answer. 

I have checked my likelihood function behavior with respect to _beta_ only, setting _A0_ as the truth and found that the likelihoods are all 0s except a very narrow range of _beta_  around the truth of _beta_, -3.0 ( the valid range is [-3.005, -2.998]). 

So I think during the 15 minutes sampling as said earlier, dynesty is just wondering around 0s of likelihood but at the end can find the valid region of likelihood. If I set the prior of  _beta_ as [-3.1, -2.9] (which in real case is not doable), dynesty only take 2 minutes to find the valid region. 

Because I have to do this for 90000 cases like this, I cann't afford to take 15 mins for only 1 case.  So I'm wondering if there is a way to get out of the region where the likelihoods are 0 with a faster speed, e.g. taking a larger time-step between each iteration?

**Comment by yaojian95** [comment]
> * Which version are you using, from main branch or 1.1 ? (you should use the main branch)

By 'main branch' do you mean 1.0.0? Before raising this issue I used 1.1 from `conda install dynesty -c conda-forge`. If I change to 1.0 from `conda install dynesty==1.0.0 -c conda-forge`,  something strange happens. One thing is that although the iteration speed is super fast,  dlogz remains to be `inf,` as following printing shows (1.0.0, with 'auto')
`321574it [03:40, 1518.18it/s, bound: 0 | nc: 1 | ncall: 321974 | eff(%): 99.876 | loglstar:   -inf <   -inf <    inf | logz:   -inf +/-    nan | dlogz:    inf >  0.500]`
And after 6 minutes an error occurs, 
`OverflowError: math range error`

To not complicate this issue,  here I still use **1.1 version**. 
> * It'd be helpful to see progress statements from dynesty .

Following is the progress printed by dynesty with 1.1, rslice sampler which takes 7 minutes and the figure shows the results.(Notice the extremely small uncertainty for `$\beta_s$`, in correspondence to the likelihood profile shown later)
`73it [01:04,  1.12it/s, bound: 0 | nc: 2211 | ncall: 101209 | eff(%):  0.072 | loglstar:   -inf <   -inf <    inf | logz:   -inf +/-    nan | dlogz:    inf >  0.500]`
`214it [03:31,  1.31it/s, bound: 0 | nc: 776 | ncall: 333478 | eff(%):  0.064 | loglstar:   -inf <   -inf <    inf | logz:   -inf +/-    nan | dlogz:    inf >  0.500] `
`3405it [07:04,  8.02it/s, +400 | bound: 19 | nc: 1 | ncall: 664250 | eff(%):  0.573 | loglstar:   -inf < -6.325 <    inf | logz: -13.972 +/-    nan | dlogz:  0.001 >  0.500]`
![image](https://user-images.githubusercontent.com/14847517/139505739-0f8654c7-36c3-446b-b7f7-fa297fd5aa5f.png)

And with `sample = 'auto'` (`unif`), which takes 23 minutes and the results are almost the same with above one. 
`1393it [09:04,  8.37it/s, bound: 281 | nc: 348 | ncall: 778603 | eff(%):  0.179 | loglstar:   -inf < -69.489 <    inf | logz: -77.131 +/-    nan | dlogz: 67.465 >  0.500]`
`1766it [11:02,  3.23it/s, bound: 478 | nc: 572 | ncall: 931584 | eff(%):  0.190 | loglstar:   -inf < -32.409 <    inf | logz: -39.946 +/-    nan | dlogz: 29.251 >  0.500]`
`3281it [22:44,  2.23it/s, bound: 1708 | nc: 518 | ncall: 1861306 | eff(%):  0.176 | loglstar:   -inf < -6.767 <    inf | logz: -14.271 +/-    nan | dlogz:  0.580 >  0.500]`
`3333it [23:18,  2.38it/s, +400 | bound: 1771 | nc: 1 | ncall: 1907440 | eff(%):  0.196 | loglstar:   -inf < -6.323 <    inf | logz: -13.785 +/-    nan | dlogz:  0.001 >  0.500]`

So indeed `rslice` sampler save about  2/3 time of `unif` but 7 mins is still a bit long for my case...

> If I had to guess, your posterior has a shape that is very non-ellipsoidal. So if you change the sampler to say rslice it'll be much faster. (but that's a speculation on my part without more info)

This following figure shows the likelihood(logL) profile with two parameters.  I set the _logL = -1000_ plane to be the region where the likelihoods are all 0. You can see how narrow the valid region of likelihood for `$\beta_s$` is . And you imagine the case where I set the prior of beta_s to [-4, -2]: almost full of zeros. 

![image](https://user-images.githubusercontent.com/14847517/139505975-ccd16fa6-ea98-43cd-a62d-2ec8fdd28de1.png)

**Comment by segasai** [comment]
Sorry, by main branch I meant the github master branch. (there are multiple improvements in it that haven't yet been released).
Regarding your problem, it seems that you have an extremely narrow posterior, potentially degenerate in one dimension. It's not obvious to me that 7 min running time with rslice sampler is a sign of any problem. 
In fact pretty much by construction of nested sampling,  the lower the ratio of the posterior volume to the prior volume the longer it will take to explore. I.e. if the ratio is R and the number of live-points is N it'll take ¬ N*R iterations. 

If you are interested in speeding things up, I can imagine several avenues.
* reparametrizing to avoid extremely thin posterior
* Moving some parts of the likelihood in the prior, i.e. pi(x) L(x) = pi^(x) * L^(x) , where L^(x) = L(x) * pi(x)/pi^(x)
* set the 'irrelevant' parts of the posterior (where logl is low enough) to essentially zero (i.e. -np.inf), so the sampler doesn't even try to explore that.

**Comment by yaojian95** [comment]
Thanks for the advices! 
I update the dynesty to the main branch and set low logL to -np.inf, and the time cost is about 2 minutes, which is a good news for me! In fact, previously I set small logL values to 1e-30, which didn't solve the problem. 

- For the second suggestion you offered,  could you give a simple example to illustrate the point? I don't understand how to absorb the likelihood into the prior. 
> Moving some parts of the likelihood in the prior, i.e. pi(x) L(x) = pi^(x) * L^(x) , where L^(x) = L(x) * pi(x)/pi^(x)

- Using the main branch with `dynesty.NestedSampler(logL.loglike, prior, npara, nlive=400, bootstrap = 0, sample = 'rslice')`,  a runtime error will occur in some cases:
>  `Afte 100 attempts, not a single live point had a valid log-likelihood! Please check your prior transform and/or log-likelihood.`

 However, when I run the sampling for a second time, this error disappears for most of the problematic cases and several cases still have this error.  I understand that there is some level of randomness during the sampling. Is this due to the _thin_ likelihood function that I have so that for some cases during the initial phase some live points cann't find the valid likelihood region? Do you have any ideas of how to avoid this kind of error?

**Comment by segasai** [comment]
> * For the second suggestion you offered,  could you give a simple example to illustrate the point? I don't understand how to absorb the likelihood into the prior.
> 
> > Moving some parts of the likelihood in the prior, i.e. pi(x) L(x) = pi^(x) * L^(x) , where L^(x) = L(x) * pi(x)/pi^(x)


The example is that if say your prior is pi(x) = U(-100,100)
and likelihood is say triangular distribution L(x) with the peak at zero and that goes to zero at +/-1
Then sampling from that is equivalent to a problem where the prior is 
pi_*(x) = N(x|0,1) 
and likelihood is L_*(x) = L(x)/N(x|0,1)*pi(x)

And the reason is that's equivalent is because 
L_*(x) pi_*(x) === L(x)pi(x)




> * Using the main branch with `dynesty.NestedSampler(logL.loglike, prior, npara, nlive=400, bootstrap = 0, sample = 'rslice')`,  a runtime error will occur in some cases:
> 
> > `Afte 100 attempts, not a single live point had a valid log-likelihood! Please check your prior transform and/or log-likelihood.`
> 
> However, when I run the sampling for a second time, this error disappears for most of the problematic cases and several cases still have this error. I understand that there is some level of randomness during the sampling. Is this due to the _thin_ likelihood function that I have so that for some cases during the initial phase some live points cann't find the valid likelihood region? Do you have any ideas of how to avoid this kind of error?

Before starting sampling dynesty needs points in the valid region of the posterior (i.e. where L>0). By default the code tries 100*nlive points sampling within the cube and none of thm are in the valid region. 
The solution for this is either 
* reparametrize the problem like I said previously to reduce the mismatch between the prior and posterior (preferred)
* generate live_points uniformly in the valid region before running dynesty and provide them through live_points (if you have some domain knowledge that allows you to do that efficiently) (not recommended)
* accept that if posterior and prior are sufficiently different it will take time to map the difference

**Comment by yaojian95** [comment]
Thanks for the detailed explanation.  I have tried to change the uniform prior to gaussian prior to match the gaussian-like posterior, but this seems to not working... 

The signal-to-noise ratio for my data is so high that the likelihood will give the estimated value of parameters with very small errors. This is like a high peak with nearly zero width. But my prior for the parameters is very wide so before starting sampling dynesty may not find the valid region of likelihood in the wide prior volume.  Can this zero-width peak be avoided by reparametrizing? 

In the 'SNR is very high' case, I have tried to increase the noise level by a factor of 10 (leaving the observed data unchanged, but increase the noise sigma in the likelihood), which means increasing the width of the peak,  it seems to work. But the error of the estimation increases also by a factor of 10.  Does it make sense to you that I increase the noise in the likelihood by 10 then divide the obtained error by 10 to get the real error? The likelihood approaches Gaussian distribution when SNR is high.  (I know this maybe not a question related to dynesty, but still I want to ask about your opinion...)

**Comment by segasai** [comment]
> Thanks for the detailed explanation. I have tried to change the uniform prior to gaussian prior to match the gaussian-like posterior, but this seems to not working...

I think you are not quite doing it correctly... 
here's an illustration on a toy problem that reduces the number of fn evaluations by a factor of 5

```python
import pickle
import numpy as np
import dynesty
import scipy.stats

original = True  # switch to false to fit reparametrized version

nlive = 100

size = 10  # box size
sig0 = 0.01


def loglike0(x):
    return -0.5 * np.sum((x / sig0)**2)


def prior_transform0(x):
    return (2 * x - 1) * size


ndim = 2
if original:
    rstate = np.random.default_rng(2)
    sampler = dynesty.DynamicNestedSampler(loglike0,
                                           prior_transform0,
                                           ndim,
                                           nlive=nlive,
                                           rstate=rstate)
    sampler.run_nested()

sig1 = sig0 * 2

N = scipy.stats.norm(0, sig1)


def loglike1(x):
    return np.sum(-0.5 * ((x / sig0)**2) - N.logpdf(x))


def prior_transform1(x):
    return N.ppf(x)


if not original:
    ndim = 2
    rstate = np.random.default_rng(2)
    sampler = dynesty.DynamicNestedSampler(loglike1,
                                           prior_transform1,
                                           ndim,
                                           nlive=nlive,
                                           rstate=rstate)
    sampler.run_nested()
```

> The signal-to-noise ratio for my data is so high that the likelihood will give the estimated value of parameters with very small errors. This is like a high peak with nearly zero width. But my prior for the parameters is very wide so before starting sampling dynesty may not find the valid region of likelihood in the wide prior volume. Can this zero-width peak be avoided by reparametrizing?

if your errors are so small and you want very fast performance, then dynesty may not be the right tool anyway. you probably can just do laplace approximation or any other sampler. 

> In the 'SNR is very high' case, I have tried to increase the noise level by a factor of 10 (leaving the observed data unchanged, but increase the noise sigma in the likelihood), which means increasing the width of the peak, it seems to work. But the error of the estimation increases also by a factor of 10. Does it make sense to you that I increase the noise in the likelihood by 10 then divide the obtained error by 10 to get the real error? 

That'll work fine, if everything's gaussian and errors are small, but if you are in that situation you don't need dynesty as welll. 

I think I'll close the issue, as I don't think there is any dynesty problem here.

**Comment by yaojian95** [comment]
Sure, thanks again for your comments.
