### ISSUE TITLE
Slice sampler has failed to find a valid point. 

### ISSUE THREAD

**Issue by wenhaoxuan** [joshspeagle/dynesty#344]
Greetings!  I'm been running some complex fits with about 25 parameters, and after a while, keep receiving this error about slice sampler failing to find a valid point. Attached is the output.  I dug into the place in dynesty where this happens, and found this occurs because` nstep_prop = 0`.  There is a comment that  `If nstep_prop = 0 something has gone horribly wrong.`  When does this become 0, and how should I fix it?  Is it an issue with sampling in a complex parameter space, or does it have to do with something on my side (e.g. the log likelihood or log prior functions?)

Note that I'm using dynesty version 1.1. 

File ...python3.8/site-packages/dynesty-1.1-py3.8.egg/dynesty/sampling.py", line 712, in sample_rslice
    fscale1) = generic_slice_step(u, axis, nonperiodic, loglstar,
File ...python3.8/site-packages/dynesty-1.1-py3.8.egg/dynesty/sampling.py", line 514, in generic_slice_step
    raise RuntimeError("Slice sampler has failed to find "
RuntimeError: Slice sampler has failed to find a valid point. Some useful output quantities:
u: [0.76336335 0.24998424 0.49567559 0.41983212 0.7772957  0.33166798
 0.29422035 0.29138277 0.3595179  0.27595009 0.23420913 0.41836311
 0.07736841 0.36564265 0.35795478 0.18123145 0.83067256 0.09813559
 0.69796109 0.28699854 0.597819   0.71162808 0.28528543 0.22770569
 0.71748225 0.05001261]
nstep_left: -5e-324
nstep_right: 5e-324
nstep_hat: 1e-323
u_prop: [0.76336335 0.24998424 0.49567559 0.41983212 0.7772957  0.33166798
 0.29422035 0.29138277 0.3595179  0.27595009 0.23420913 0.41836311
 0.07736841 0.36564265 0.35795478 0.18123145 0.83067256 0.09813559
 0.69796109 0.28699854 0.597819   0.71162808 0.28528543 0.22770569
 0.71748225 0.05001261]
loglstar: -19800.90192191184
logl_prop: -19801.581890347155
direction: [-0.05034865 -0.00019064 -0.00499202 -0.00309533  0.00974036 -0.01227736
 -0.00302642 -0.00503653  0.00154991 -0.00244959 -0.00896804  0.01269093
 -0.01178801 -0.0508827   0.05459159  0.00608787 -0.00530888 -0.01745749
 -0.00897818  0.00169736  0.00199169 -0.01654563  0.01481171 -0.00530902
 -0.00212835  0.07214545]

**Comment by segasai** [comment]
Please use the master branch from github. slice sampling is dramatically more stable there.

**Comment by wenhaoxuan** [comment]
Thanks, I updated to the master branch, and will see if the issue persists or not. I did notice quite a few discrepancies between version 1.1. and the master branch however.  Mostly, it appears the `sampler.results` object has changed type? My previous ways to read and work with sampler.results no longer works now.  Here,` sampler = NestedSampler(etc.)`

**Comment by wenhaoxuan** [comment]
Also, I just got the same error with the current master branch. Would you suggest switching to a different sampling method (I'm using rslice now), or trying the dynamicsampler?  

 ```
.../dynesty/sampling.py", line 612, in sample_rslice
 .../dynesty/sampling.py", line 414, in generic_slice_step
RuntimeError: Slice sampler has failed to find a valid point. Some useful output quantities:
u: [0.55994307 0.18971545 0.27826619 0.05043596 0.83823085 0.01235626
 0.34299792 0.0894761  0.26461571 0.98565665 0.63519326 0.71378108
 0.31039994 0.57348298 0.67560711 0.38702999 0.20458486 0.65203994
 0.04258769]
nstep_left: -1e-323
nstep_right: 3.5e-323
nstep_hat: 4.4e-323
```

**Comment by segasai** [comment]
I think there are two possible explanation of the error you see
* Your likelihood has some sort of weird discontinuities, i.e. you could have isolated single  points that are much higher in logl than surroundings (or your likelihood is noisy or stochastic)
* there is a bug in a sampler 

Based on what you see I think the first option is more likely, but it's certainly possible that the second option is true but more information is needed.  Ideally a full backtrace and all the previous dynesty output as well as how you actually run dynesty.

**Comment by wenhaoxuan** [comment]
Thanks @segasai for your help. The first option is indeed likely in my case, since I'm working on a complex fit (15-25 parameters) that involves radiative transfer, and certain regions could be much lower in logl than others.  How would you recommend trying to go around this?  I can only think about shrinking the prior space, but that's not very ideal.

**Comment by segasai** [comment]
If your posterior is actually non-determinstic (i.e. if you ran it with the same parameters and it can give you a different logl) then you can't really sample it and you really should first make it determinstic. 
if it is deterministic, but just noisy that shouldn't be a problem. The problem will happen only if you can have width=0 peaks (ie like delta f-n)
if you have that issue, I'd say you may try the ellipsoidal sampler (although that likely will be slow in highdim).

**Comment by wenhaoxuan** [comment]
Thanks! My posterior is deterministic. By the ellipsoidal sampler? Are you referring to a particular bounding distribution (e.g. "multi") or sampling option ("rslice")?  It seems like by default bound="multi" is used, and from my error traceback, sample="rslice" was used.

**Comment by segasai** [comment]
I meant sampler='unif'

But TBH I'm not convinced the diagnosis of the problem is correct. I think looking at the logl behaviour is needed to confirm that. i.e. looking at logl along a single line (for example going though the problematic point where the error happened)
