### ISSUE TITLE
Issue template

### ISSUE THREAD

**Issue by segasai** [joshspeagle/dynesty#345]
Given a set of recent issues reported here, 
I think we need to setup a template for issues (only repo admin can do that)
People need to report the exact version, need to tell how exactly they run dynesty, so we see all the options used. Also we need to ideally see the output of the progress report.

**Comment by joshspeagle** [comment]
Hm. This seems straightforward enough for bug reports, while still leaving things open for more general questions and feature requests. Let me try and add this in now...

**Comment by joshspeagle** [comment]
Okay, that should be fine to start I think!

**Comment by segasai** [comment]
Yes, thanks, looks good
