### ISSUE TITLE
Unsure about Posterior Errors

### ISSUE THREAD

**Issue by Tomariebenami** [joshspeagle/dynesty#358]
Hello,
Lately I've been working on using Dynesty to investigate light-curves, and am working with a 10 parameter fit, which up to now is working well, using the Dynamic Sampler:

` dsampler = dynesty.DynamicNestedSampler(loglikelihood=lnlike,
                                                    prior_transform=prior_transform,
                                                    ndim=10,
                                                    pool=Pool(), queue_size=qs,
                                                    sample='rwalk')

dsampler.run_nested(nlive_init=1000, nlive_batch=1000)`

I've been trying to understand how to best estimate the error on my parameters.

I've started by using the mean and covariance function - `mean_and_cov()`, and have read over the 'Nested Sampling Errors' in the documents, but unlike with evidence estimation, from my understanding in order to implement the errors correctly for the posterior distribution, is to use the `resample_run()` function. 

I'd appreciate your input at to whether the way I calculated the parameter uncertainties, using the `mean_and_cov()` function after resampling, is the correct way to go. 

Thanks!

**Comment by segasai** [comment]
Under the assumption that your run had enough live-points and the posterior is properly sampled, my suggestion would be to take equally weighted posterior samples and use that to estimate whatever summary statistics you are interested in.

**Comment by segasai** [comment]
Because equally weighted samples can be passed through any summary statistics routine without an effort. I.e. you can calculate   means, std, percentiles, covariances etc. Sure for the caclulation of Means and covariances there is a dedicated code that can take weighted samples, but  IMO if you are in the regime where the difference between weighted sample and unweighted sample calculation is significant, you need more samples anyway. (this is just my personal view) .

**Comment by Tomariebenami** [comment]
Thanks you for the input! I'm right now inspecting this to check if I might of have not used enough live points and under-sampled the posterior. 

Out of curiosity, when choosing how many live points, I tried to follow what was written in the docs - 50 live points per expected mode. However, in the the case that one does not know the amount of modes that the posterior might have, how should one go about choosing the right number of live points? Just iteratively or is there a smarter way?

**Comment by segasai** [comment]
I'm not aware of  a generic recipe for this problem. 

There are two approaches of thinking about this that may be useful. Each mode will have some part of the volume where the mode "dominates" (i.e. where this mode is the local maxinum). If these volumes are very small, you may need a large number of live points to discover them (i.e. of the order of 1/V) That's the constrain coming from just discovering the mode.

Another constrain is different. if you have n-dimensional posterior, then to properly characterize the n-dimensional ellipsoid you need more than n+1 point, therefore for m-modes you would want more than m*(n+1) points. 

Those are the factors to consider.

You can somewhat alleviate these issues by running many batches after your run with .add_batch(mode='manual')

**Comment by segasai** [comment]
I assume the question was answered. I'm closing the issue.
