### ISSUE TITLE
Title Quantiles

### ISSUE THREAD

**Issue by mkplummer** [joshspeagle/dynesty#363]
Good afternoon! This is probably an easy fix, but I can no longer find the API for dyplot.corner.

I was curious how to set the title quantiles to values other than the default (appears to be 2sigma). By setting quantiles = desired quantiles, I only change the dottle lines bounds not the values in the title.

Thank you!

**Comment by segasai** [comment]
title_quantiles is what you want likely
https://github.com/joshspeagle/dynesty/blob/69635b3e4ac5a692e17482b082e324f066e578b8/py/dynesty/plotting.py#L1170

**Comment by joshspeagle** [comment]
@segasai pointed you to the right place, but it looks like I might've accidentally broken the API portion of the docs... whoops! Hopefully that can be restored soon.

**Comment by segasai** [comment]
@joshspeagle it seems that indeed py.dynesty.* in .rst files is incorrect. What's needed is 
```
sys.path.insert(0, os.path.abspath('../../py'))
```
in docs/conf.py instead

Will you do that ? or should I ?

**Comment by joshspeagle** [comment]
if you have a moment feel free to push it. Otherwise, I can do it later tonight.

**Comment by segasai** [comment]
Done. (in the latest version of the docs).
Thanks @joshspeagle  for checking the actual doc page, I haven't bothered looking there, when I first answered here

**Comment by mkplummer** [comment]
Thank you for the help!

I have been putting title_quantiles = (0.16,0.5,0.84) into dyplot.corner(), but I get this error:
<img width="542" alt="Screen Shot 2022-03-31 at 8 00 54 PM" src="https://user-images.githubusercontent.com/80552610/161169346-007bb1c0-a82d-4c76-ae27-9ea74993d9c4.png">

**Comment by mkplummer** [comment]
I updated to the newest version, and it is working now. Thank you again!
