### ISSUE TITLE
Recommended number of live points for high-dimensional rslice

### ISSUE THREAD

**Issue by asmasca** [joshspeagle/dynesty#367]
I've been using the slice sampler for a while and I found that using "nlive = ndim*(ndim+1)//2" (as I remember reading in some part in the documentation) works fine for almost all (or all) the cases I study. It provided a good exploration of the parameter space and consistent results from run to run. Now with the latest updates I'm moving towards the random slice sampling strategy and, while it's much faster, I'm finding that sometimes with the same number of live points I'm not getting consistent results from run to run. It often requires more live points to get to a posterior distribution I can reproduce over and over. 

Do you have a recommendation for a good number of live points to use in a fairly general case?

**Comment by asmasca** [comment]
I would try to provide an example, in the coming days. 

After reading your comment I think it might be that I'm in the situation of having a large prior volume and a very small posterior volume. The posterior distribution should be unimodal (assuming a correct model and perfect data), so in principle it might be that I don't have enough live points to discover the consistently discover the global maximun. 

With the "old" slice sampling strategy it seems that they were enough, but admittedly it was something like 5 times slower, so there is some margin to add extra live points while still being faster to compute.

**Comment by segasai** [comment]
I've found that there is an entry in the FAQ regarding the number of live points https://dynesty.readthedocs.io/en/stable/faq.html 
as well. 
And, I'd certainly be interested in seeing examples where you think the current behaviour is less stable than it was previously (for the same sampler).
Regarding what the reasone for what's happening in your case, I won't try to speculate without seeing  some details. 

Also, you may want to use the version from master, as there was a pretty annoying bug fix fixed #364 there

**Comment by asmasca** [comment]
Just to clarify, it's not "for the same sampler". The diferences I'm seeing are a result of moving from the "slice" sampler to the "rslice" sampler.

**Comment by segasai** [comment]
Ah, I see, I didn't quite get that. So it's not a regression, it's difference in performance between rslice and slice. 
I'd certainly like to see where rslice performs worse than slice. 
It is also possible that the number of steps we do for rslice is not enough.
I.e. for slice the there are 3n steps per iteration (i.e. looping 3 times over all dims), while for rslice it's (3+n). 
You may want to try to bump the slices parameter and see how it affects things.

**Comment by asmasca** [comment]
To make sure I got it right, before I go actually changing things inside the dynesty code. Can that be done with this parameter (below)?  or do I need to excplicitly edit the" _get_walks_slices" function?

"slices:int, optional
For the 'slice', 'rslice', and 'hslice' sampling options, the number of times to execute a “slice update” before proposing a new live point. Default is 5. Note that 'slice' cycles through all dimensions when executing a “slice update”."

**Comment by segasai** [comment]
You don't need to change anything in the source code. You just change the slices option here: https://dynesty.readthedocs.io/en/latest/api.html#dynesty.dynesty.NestedSampler
