### ISSUE TITLE
Changed behaviour of "Results" class in v>=1.2?

### ISSUE THREAD

**Issue by MNGuenther** [joshspeagle/dynesty#369]
**Describe the bug**
Previously (in all versions <1.2), we could do the two following things:

A)
```
results = sampler.results
results2 = results.copy()
```

B)
```
results = sampler.results
f = gzip.GzipFile(os.path.join(config.BASEMENT.outdir,'save_ns.pickle.gz'), 'wb')
pickle.dump(results, f)
f.close()
results = pickle.load(f)
```

**Setup**
I am running dynesty version 1.2, 1.2.1, and 1.2.2 from PyPI.

**Bug**
For scenario A) we now get: `AttributeError: 'Results' object has no attribute 'copy'` This is not a big problem, as we can simply use the `copy` package instead. But out of curiosity, why was this feature removed? 
The behaviour I expected was that it would still be able to create a copy of the `results` object. 
To reproduce the behaviour I see, please see the examples above.

For scenario B) we now get: `TypeError: 'Results' object does not support item assignment` triggered by the line `results = pickle.load(f)`. How can we solve this and still load the pickled files? 
The behaviour I expected was that it would still be able to load the `results` object from the pickled file.
To reproduce the behaviour I see, please see the examples above.

**Additional context**
Our allesfitter code uses dynesty as one of the sampler choices.

**Comment by segasai** [comment]
I've commited the change that adds the .copy() method for the results.

**Comment by MNGuenther** [comment]
Ah brilliant! Thanks for your quick reply, @segasai 

The reason why you could not replicate the issue is that it hinges on the change from v<1.2 to v>1.2. See here:

import numpy as np
import dynesty
import pickle
import gzip

printing = False

nlive = 100

size = 10  # box size


def loglike(x):
    return -0.5 * np.sum(x**2)


def prior_transform(x):
    return (2 * x - 1) * size


def save_pickle(mode):
    # test of pickling functionality
    ndim = 2

    kw = {}
    if mode == 'dynamic':
        sampler = dynesty.DynamicNestedSampler(loglike,
                                               prior_transform,
                                               ndim,
                                               nlive=nlive,
                                               **kw)
    elif mode=='static':
        sampler = dynesty.NestedSampler(loglike,
                                        prior_transform,
                                        ndim,
                                        nlive=nlive,
                                        **kw)
    sampler.run_nested(print_progress=printing, maxiter=100)
    
    f = gzip.GzipFile('save_ns_results_'+mode+'.gz', 'wb')
    pickle.dump(sampler.results, f)
    
    
def load_pickle(mode):
    f = gzip.GzipFile('save_ns_results_'+mode+'.gz', 'rb')
    results = pickle.load(f)
    print(results)


'''
First, do
pip install dynesty==1.1
and then run dynesty to save the pickle
'''
# save_pickle('static')
# save_pickle('dynamic')


'''
Then, do
pip install dynesty==1.2.2
restart the kernel and try to load the pickle
'''
# load_pickle('static')
# load_pickle('dynamic')

**Comment by segasai** [comment]
In my opinion, we should not guarantee that results classes are compatible between major version releases. (we shouldn't try to actively break them either, but the 1.2 change was necessary IMO) 

For a very specific case of pickled Results class from dynesty<1.2, the best way to proceed would be to save
result.items()  -- i.e. essentially key,value pairs for the dictionary and use that to initialize the new Results class.

I.e. this code works fine if you save the results with dynesty 1.1 and restores as 1.2 

```python
import numpy as np
import dynesty
import dynesty.results as dr
import pickle
import sys

printing = False

nlive = 100

size = 10  # box size

def loglike(x):
    return -0.5 * np.sum(x**2)

def prior_transform(x):
    return (2 * x - 1) * size


def test_pickle1():
    ndim = 2
    rstate = None

    sampler = dynesty.DynamicNestedSampler(
        loglike,
        prior_transform,
        ndim,
        nlive=nlive,
        rstate=rstate,
    )
    sampler.run_nested(print_progress=printing, maxiter=100)
    with open('/tmp/xx.pkl', 'wb') as fp:
        # S1 = pickle.dump(sampler.results, fp)
        S1 = pickle.dump(list(sampler.results.items()), fp)


def test_pickle2():
    with open('/tmp/xx.pkl', 'rb') as fp:
        # res = pickle.load(fp)
        res = dr.Results(pickle.load(fp))
        print(res)


if __name__ == '__main__':
    if sys.argv[1] == '1':
        test_pickle1()
    if sys.argv[1] == '2':
        test_pickle2()

```

**Comment by MNGuenther** [comment]
Sounds good, we will encourage our users to keep the dynesty version the same for a given project. And when accessing older projects, it is easy enough to swiftly change the version via `pip install`.

**Comment by segasai** [comment]
great!
But also there are strong reasons to migrate to dynesty=1.2 (for correctness and performance reasons), so you may want to communicate that as well.
