### ISSUE TITLE
Live points with Dynamic Sampler

### ISSUE THREAD

**Issue by pacargile** [joshspeagle/dynesty#37]
The user defined "live_points" input is not being sent to the DynamicSampler method within the DynamicNestedSampler function.

**Comment by joshspeagle** [comment]
This has now been fixed in 1757c8e45b17dd5061a7f583024bd051b86c0901. Live points can be passed directly in `run_nested()` (if sampling implicitly) or `sample_initial()` (if sampling explicitly).
