### ISSUE TITLE
Reinitializing pool with multiprocessing

### ISSUE THREAD

**Issue by natashabatalha** [joshspeagle/dynesty#371]
**Bug/Question**
I would like to add more samples to an existing set of runs but do not know how to do so with the addition of a multiprocessing pool. I am using dynesty version 1.2.2. 

**Setup**
Following the example in `test_pool.py`, I initialize a pool via NestedSampler by doing e.g.:
```
#test_pool.py
pool = mp.Pool(30)
with pool:
    sampler = NestedSampler(loglike, ptform, ndim,pool=pool,
                                            queue_size=30) 
    sampler.run_nested(maxcall=1000) 
dill.dump(sampler, open('test.dill','wb'))
```
After this initial run, I would like to build on it on it by reopening up the pool. If I simply perform:
```
sampler = dill.load(open('test.dill','rb'))
sampler.run_nested()
```
it works but without parallelization. Is there a way to add more samples in parallel? 

For example, something like this: 

```
saved_sample = dill.load(open('test.dill','rb'))
newpool = mp.Pool(30)
with newpool:
    saved_sample.pool = newpool
    saved_sample.run_nested()
```

Thanks for your help!

**Comment by segasai** [comment]
This should work
```python
with newpool:
        sampler.pool = pool
        sampler.loglikelihood.pool = pool
        sampler.M = pool.map
        sampler.run_nested()
```

It is somewhat unwieldy, as there is no official interface for that, but it will work.
I can't promise that this interface will stay as this is in the future.

**Comment by segasai** [comment]
I'll close this issue, but I created the #374 issue to track development of the interface for easier restarts
