### ISSUE TITLE
Progress is not printed properly

### ISSUE THREAD

**Issue by Nicholaswogan** [joshspeagle/dynesty#372]
When running a nested retrieval, sometimes the progress does not print properly. For example:

```sh
(rfast) [wogan@silver examples]$ python parallel_example.py
eff(%):  3.552 | logl*:   -inf<-609.5<   inf | logz: -624.8+/-nan | dlogz:  471.4>   0.0                                   
```

This tends to happen when running a script from a MacOS or Linux terminal.

**Comment by segasai** [comment]
I see nothing wrong here. If you see something wrong, please follow the bug  template, explain what you do (ideally in reproducible manner), what you see and what you expect.

**Comment by joshspeagle** [comment]
It actually is supposed to depend on the size of the terminal to try and avoid overflow issues where the output doesn't properly overwrite. See the associated print function for details on how this is done.
