### ISSUE TITLE
Question about initial live points

### ISSUE THREAD

**Issue by Jammy2211** [joshspeagle/dynesty#378]
I am working on a problem where it is common for the model-fit to infer local maxima. This occurs for dynesty, but is pretty much a problem for whatever model-fitting algorithm I use (MCMC, MLE, etc.). 

To mitigate the issue, I am able determine an initial set of live points that are near the global maxima (I won't give details of how I am able to do this, but basically it involves me fitting a simpler likelihood function lots of times to generate these points). For something like an MCMC fit, I can then safely use this set of points as the starting point for my walkers.

My question is simply whether passing Dynesty a set of initial points in an analogous fashion is a "safe" or "reasonable" thing to do?

My main concern is that these initial points I would pass dynesty are not randomly drawn from the priors and are in fact a very biased set of points relative to the priors. Given that when no initial live points are passed to dynesty it randomly draws points from the priors, my question is whether this an important aspect of the dynesty / nested sampling process and whether passing it a biased set of points might lead to error underestimation or other weird results?

**Comment by segasai** [comment]
If you provide the starting points not from the prior the results will *not* in general be accurate. As the sampler only moves higher in likelihood.
If you have large parts that are irrelevant from your point of view, you can set there the logl value to -large value and focus only on narrow region around the maximum but if you provide the initial points they still need to be uniform samples subject to L>L* constraint

**Comment by Jammy2211** [comment]
> If you provide the starting points not from the prior the results will not in general be accurate. As the sampler only moves higher in likelihood.

I am confident I can get a set of points that are high likelihood and "surround" the highest likelihood models (which I would hope the sampler than converges on). 

In that sense, if the sampler only moves higher in likelihood it would probably be ok.

> If you have large parts that are irrelevant from your point of view, you can set there the logl value to -large value and focus only on narrow region around the maximum but if you provide the initial points they still need to be uniform samples subject to L>L* constraint

We indeed already remove large regions of this parameter space by returning a logl value of -1.0e99 (or something very small). 

The problem is that as the model dimensionality increases this resampling approach can pretty much end up being every live point, such that dynesty stops running or keeps randomly guessing live points indefinitely. 

We are able to create a set of initial live points that are highish likelihood solutions pretty quick, hence why we're hoping these could be used as the dynesty initial samples.

**Comment by segasai** [comment]
* If the dynesty stops running (and similar) that is a problem that likely needs fixing (or you need to change some settings).
* Regarding your initialization, I'm still quite sceptical. If you can be quite confident that the initial samples are a fair representation of L>L*  uniform samples, you can proceed, but if you are not sure, you may experience biases. 

TBH, it's a bit hard to make suggestions, without a specific example. 

The problem is that if you have say isolated modes, the number of live points associated with each of them needs to be proportional to their volumes, which is hard to to achieve with your scheme as far as I can see.
