### ISSUE TITLE
initialize with saved results

### ISSUE THREAD

**Issue by joshspeagle** [joshspeagle/dynesty#39]
Users might want to "continue" a previous run after they've dumped the set of previous results to disk. Either:
- add in functionality allowing a previous `Results` dictionary to be used to initialize a sampler, or
- add an example showing how to do this manually using pre-existing features (initializing live points manually and then combining the runs using `merge_runs`).

**Comment by joshspeagle** [comment]
While this would be nice, I realized (1) this feature isn't available (as far as I can tell) in `emcee` (and doesn't seem to be a problem) and (2) users could probably dump the entire `NestedSampler` to file. I still might try to show how to hack this using pre-existing features in a future demo though.

**Comment by joshspeagle** [comment]
I've since realized this even though this feature might be a bit of a pain to implement, it would be immensely useful so that users can continue sampling from where they left off, transfer results, etc. I've re-opened the issue and hope to add this functionality soon-ish.

**Comment by joshspeagle** [comment]
Okay, almost 2 years later and this early issue is finally getting wrapped up, although not maybe the way it was intended. Here's a summary of the basic original idea:

- It would be nice to continue where you left off if you want to add some more samples later.

Turns out there are a few problems with this. The biggest is that adding more samples to an existing run is trivial assuming the sampler is initialized, both for `NestedSampler` and `DynamicNestedSampler`. So there's no benefit there. If you want to add samples earlier in the run for `NestedSampler` (i.e. increase the number of live points when you originally didn't want to), you might as well just run a separate instance and use `merge_runs`. The `DynamicNestedSampler` also has a bunch of options for adding in samples.

So that means this option would be most useful for trying to add results *after* these objects have been dumped, when only the final set of `results` are left. If this happens after a run has fully completed, then we're in the same situation as before where it makes more sense to just run something new and combine it with the old results with `merge_runs`. If, however, we're in a situation where a run failed because it *terminated before convergence*, then we essentially have bigger problems, since there's no guarantee (1) that I could use the incomplete results to reconstruct the initial state of the sampler and (2) that the results are reliable anyway. In this case, it's better to just restart and combine the incomplete old run with a complete new run (improving your resolution where you had previously computed samples).

Given this reasoning, I've updated the documentation to highlight the `merge_runs` feature in the Crash Course, Getting Started, and FAQ pages, and am just shuttering this for now.

**Comment by smutch** [comment]
Hi @joshspeagle. I'm currently investigating using dynesty for a project but it involves doing runs on an HPC machine where the initialization step may time out due to the expense of the likelihood. So far I've been using nestle and made [some changes](https://github.com/smutch/nestle) to allow the its sampler to be pickled and checkpointed at regular intervals. It can then be restarted from where it left off if needed.

Would this be something that might be possible with the initialization phase of dynesty and, if so, is this something you would consider as a PR (assuming I could get it to work :))?

Also - thanks for releasing a great piece of code!

**Comment by joshspeagle** [comment]
You can run the sampler as a generator using some of the more advanced functionality (I have some demos in the notebooks, and also in the docs), which allows you to periodically dump pickles to disk that you can restart later. There are some restrictions on this (see #181) that require you to re-initialize a few things when you load the pickled sampler back in, but otherwise you should be able to do this.

**Comment by smutch** [comment]
Perfect! Thanks for this. I'll give this a go...
