### ISSUE TITLE
Implementing an elliptical slice sampler

### ISSUE THREAD

**Issue by mvsoom** [joshspeagle/dynesty#426]
I want to implement a custom slice sampler, namely the [elliptical slice sampler (ESS)](https://arxiv.org/abs/1001.0175). Context: I have a problem with Gaussian priors for which ESS works well and I would like to check if I can transport this efficiency to nested sampling.

I was browings the code today to see whether it would be possible. It seems like I only have to reimplement the [`generic_slice_step`](https://github.com/joshspeagle/dynesty/blob/2d49cf9104e417a44ada7f2f1d013cbfee0acf01/py/dynesty/sampling.py#L356) function. Is that right (first question)? Does slice sampling in dynesty take into account the bounding distributions as is done for example in [`generic_random_walk`](https://github.com/joshspeagle/dynesty/blob/2d49cf9104e417a44ada7f2f1d013cbfee0acf01/py/dynesty/sampling.py#L154)  (second question)?

Thanks!

**Comment by segasai** [comment]
Hi, 

My suggestion is to implement the 
sample_ellslice similarly to sample_rwalk, sample_rslice. 
Then you should be able to provide that function directly to dynesty.NestedSampler, i.e.
NestedSampler(sample=sasmple_ellslice)

Regarding the existing slice sampling, yes it does take into account boundaries, it is used to choose the scale of the step, and 'metric' (using the ellipsoid parameters to generate random directions) 

Also, I'll say that I am hoping to rewrite/restructure the sampling structure in dynesty ( #391 ) to make it more easy to add new samplers, so the integration of the new sampler into dynesty (if that's your goal), may wait till this is implemented.

**Comment by mvsoom** [comment]
OK, thanks for the reply!
