### ISSUE TITLE
Errors in declaring checkpoint file. 

### ISSUE THREAD

**Issue by Buding820** [joshspeagle/dynesty#433]
** Dynesty version **
Specify the exact version, and how you installed it (pip/git)
I am using `dynasty` version 2.1.0, and install it via `git` 
** Your question **
I am using `dynesty` as my sampling algorithm in my project, but I am encountering an error when declaring the `checkpoint file` in the `run_nested` function. This may be due to my `likelihood` function needing to call the `Popen` function from the `subprocess` library. The error message prompted by `dynesty` is as follows:

> Traceback (most recent call last):
> ...
> File `".../dynesty/py/dynesty/utils.py",` line 2318, in `save_sampler `
> `pickle_module.dump(D, fp)`
> TypeError: cannot pickle '`PyCapsule`' object 

I am wondering how to modify my code, or if there is another way to save only the data when checkpointing, and then restore from the data file during recovery, instead of saving the entire sampler object?

**Comment by segasai** [comment]
Please take a look at the last question of the FAQ that addresses that specific issue

https://dynesty.readthedocs.io/en/stable/faq.html

**Comment by Buding820** [comment]
Thank you, my code is running, and looks fine
