### ISSUE TITLE
"acceptance walk" implementation in the sampling methods?

### ISSUE THREAD

**Issue by lalit-pathak** [joshspeagle/dynesty#445]
dynesty (2.1.1)

Is there a new sampling method (apart from `'unif'`, `'rwalk'`, `'slice'`, `'rslice'`, `'hslice'`) called `'acceptance walk'` in the latest dynesty version (2.1.1)? I actually read it in a research paper. I thought it is implemented in the dynasty. However, when I searched for it, I couldn't find it. Could you please let me know whether it is indeed the case?

**Comment by segasai** [comment]
The sampling methods provided by dynesty are:  'unif', 'rwalk', 'slice', 'rslice', 'hslice' and nothing else. 

It is possible however to use external user provided samplers.
