### ISSUE TITLE
The loglstar is always -inf<-inf<inf

### ISSUE THREAD

**Issue by Sunnnsh** [joshspeagle/dynesty#447]
Hi, I currently using dynesty to do some sample and I find that the loglstar is always -inf<-inf<inf. I checked the log-likelihood and its value is around 300000~50000000. Is this issue occur because my log-likelihood value is too large? Or how can I solve this issue?

Thanks!

**Comment by segasai** [comment]
Hi, 

I am afraid you don't provide enough information to assess if there is any issue at all.
Also there is a question in FAQ on a related issue
https://dynesty.readthedocs.io/en/stable/faq.html#sampling-questions

If you think there is an issue, please provide enough information to understand what you do, what you see and why/if you think something is wrong.

**Comment by segasai** [comment]
Sorry for delayed reply, but it seems that this specific question is addressed in FAQ
"There are inf values in my lower/upper log-likelihood bounds! Should I be concerned?"
