### ISSUE TITLE
An issue about dyplot

### ISSUE THREAD

**Issue by Krowkosy** [joshspeagle/dynesty#448]
Hi, 
I have a question about dyplot. When I use dyplot to create a corner plot, I noticed that it only shows a small region around the converged values. How can I expand the plot range to match the priors I have set?

**Comment by segasai** [comment]
you can use the span= keyword to specify the range for each dimension 
see https://dynesty.readthedocs.io/en/stable/api.html#dynesty.plotting.cornerplot
