### ISSUE TITLE
Documentation incorrect for Pool helper object

### ISSUE THREAD

**Issue by emprice** [joshspeagle/dynesty#454]
The [documentation for `Pool`](https://github.com/joshspeagle/dynesty/blob/5d4c8a318bdb6d1306754de385a418865d23ba70/py/dynesty/pool.py#L50) gives conflicting information about how to use `Pool`. Neither `pool.like` nor `pool.loglikelihood` are valid attributes; the correct attribute in the current version is `loglike`, which doesn't appear in the documentation, just the source. I'm guessing this has changed over versions and the documentation just wasn't updated to reflect the new attribute name.

**Comment by segasai** [comment]
Thanks.  Fixed 241acc7c5054b9c930c3a073fe71b195127e3864
