### ISSUE TITLE
Questions about dyplot.cornerplot

### ISSUE THREAD

**Issue by Sunnnsh** [joshspeagle/dynesty#458]
Hi, 
I'm sorry to bother you. I want to ask about dyplot.cornerplot. How can I plot the results of two dynesty runs on a single corner plot using dynesty.cornerplot?
How can I make the central region not filled with color?
![微信图片_20231107152134](https://github.com/joshspeagle/dynesty/assets/79961258/2b251ebb-831c-46df-8ab7-bf8311d9a445)
and or make them color-filled with levels as shown in the following figure?
![微信图片_20231107152255](https://github.com/joshspeagle/dynesty/assets/79961258/66242f91-3134-488d-a433-892d7bcbb2ad)

**Comment by joshspeagle** [comment]
So at its core, `dynesty.plotting.cornerplot` passes certain arguments (here the relevant one is the `hist2d_kwargs` at the [corresponding API](https://dynesty.readthedocs.io/en/latest/api.html#dynesty.plotting.cornerplot)) through to other plotting internals to plot up the (smoothed) 1-D and 2-D histograms. The `_hist2d` method for the 2-D contours can be found [here](https://dynesty.readthedocs.io/en/latest/api.html#dynesty.plotting._hist2d), which describes what options are theoretically available to change the settings on these.

**Comment by Sunnnsh** [comment]
Thank you very much! 
I have two dynesty results, how can I use dynesty.plotting.cornerplot to plot them on one corner plot? I have tried using a loop, but it doesn't work.

**Comment by Sunnnsh** [comment]
Thank you very much!
I have two dynesty results, how can I use dynesty.plotting.cornerplot to plot them on one corner plot? I have tried using a loop, but it doesn't work.

**Comment by joshspeagle** [comment]
You should get the fig, axes objects returned as part of the cornerplot method call. You should be able to feed one/both (I forget the exact syntax) back in as an argument to a future plotting call, which will then overplot the results on the same figure.

**Comment by Sunnnsh** [comment]
Thank you!
