### ISSUE TITLE
Discretised prior in Dynesty

### ISSUE THREAD

**Issue by FengqiuAdamDong** [joshspeagle/dynesty#463]
** Dynesty version **
Specify the exact version, and how you installed it (pip/git)
2.1.1 pip
** Your question **
Hello, my question centers around discretised prior distributions. In my case, I have a binomial likelihood and I want to sample over N, the number of trials. Is there any way to do this in dynesty?

**Comment by segasai** [comment]
Yes, I would say so. 

At least I did it by basically assuming a continuous parameter with some prior between 0..K which you can then truncate to an integer. 
I.e. this is implemented here https://github.com/segasai/mdf_modeling_paper (for this paper https://ui.adsabs.harvard.edu/abs/2023MNRAS.520.6091D/abstract )

At least for me it worked fine, but I wouldn't rule out a possibility of some convergence difficulties, depending on the problem.

**Comment by segasai** [comment]
Specificaly for my case I basically used the prior transform like this  
n = (10**(-1 + (MAXLOGN+ 1) * x))
and then truncating to an integer in the likelihood

**Comment by FengqiuAdamDong** [comment]
Thank you, I read the paper, and it seems like you added a small level of deterministic noise to the likelihoods. But in the footnote, you say that this is not needed anymore in the new dynesty version. Is that correct?
![image](https://github.com/joshspeagle/dynesty/assets/47464730/00034997-30e0-4e00-9298-c91ac800169a)
![image](https://github.com/joshspeagle/dynesty/assets/47464730/810aa123-bb14-4e0e-bd11-30a1b9e5f8dc)

**Comment by segasai** [comment]
Yes the 2.1 version does not require any artificial noise as it supports likelihoods with  plateaus.

**Comment by FengqiuAdamDong** [comment]
I implemented a discrete prior transform, specifically this one https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.randint.html
And everything seems to work.
Is there any reason to prefer one approach over another?

**Comment by segasai** [comment]
If the PPF of the distribution maps U(0,1) into discrete numbers, that is probably fine as well. I personally wasn't sure if the discreteness after prior transform is an issue or not (maybe not)
