### ISSUE TITLE
How to access posteriors?

### ISSUE THREAD

**Issue by mkplummer** [joshspeagle/dynesty#470]
** Dynesty version **
1.2.0

** Your question **
I apologize for the simplicity of this question, but I am having trouble figuring out how to access the posterior distributions which are plotted via the dynesty corner plot module. I notice that the results.samples are not exactly the same as the true posteriors and I think this is because they are weighted. Any help would be greatly appreciated. Thank you!

**Comment by segasai** [comment]
Please check the demos, i.e. this one
https://github.com/joshspeagle/dynesty/blob/master/demos/Demo%201%20-%20Overview.ipynb
that talks about how to get the equally weighted samples.
See also the docs here:
https://dynesty.readthedocs.io/en/latest/quickstart.html#basic-post-processing
