### ISSUE TITLE
Passing kwargs and args to likelihood function

### ISSUE THREAD

**Issue by pacargile** [joshspeagle/dynesty#48]
Could you add args= and kwargs= when initializing the NestedSampler object that would take an argument list and/or a keyword dictionary that get passed to the likelihood function? This would allow for likelihood functions of the type lnlike(v,*args,**kwargs), and would allow for backwards compatibility with EMCEE.

**Comment by joshspeagle** [comment]
That's fair. I'll try to get to this at some point next week.

**Comment by joshspeagle** [comment]
As referenced in the commit, this adds support for both providing args and kwargs to the `loglikelihood` *and* `prior_transform` function via some new input arguments using the same scheme as ``emcee``. I did some brief consistency tests and didn't find anything breaking in both the serial and parallel case. Let me know if you find any bugs.
