### ISSUE TITLE
Sampling narrow posteriors in wide priors

### ISSUE THREAD

**Issue by asmasca** [joshspeagle/dynesty#484]
** Dynesty version **
Dynesty 2.1.1 PIP

** Your question **
Do you have any suggestion on how to configure the sampler to make it more sensitive to narrow posteriors? I'm dealing with a case in which (with respect to the most important parameter) the posterior is a fraction 3e-5 of the prior. In my definitive analysis the prior shouldn't be made much narrower, due to analysis conventions. Dynesty sometimes finds it and sometimes completely misses it. Other than that, the posterior is expected to be unimodal. 

Is there any recommendation on how to configure the sampler to deal with these type of scenarios? (other than finding a parametrization in which the posterior might not be that narrow)

**Comment by segasai** [comment]
Hi, 

if the posterior occupies a tiny isolated volume of the prior, lets' say epsilon, you'd need at least 1/\epsilon samples to find it. 
The possible ways to help that are: 
1) Increase the number of live-points
2) add more batches manually, i.e. add_batch(mode='manual', bounds=[-np.inf,..]), which will essentially give more samples in the prior and will help to discover the posterior
3) run independent nested sample runs and merge them 
 Maybe there are others, but I'd probably go for 2)

**Comment by asmasca** [comment]
Hi, apologies for taking very long to come back. Increasing the number of live points 5x did the trick and made dynesty consistently discover and sample the mode.

**Comment by segasai** [comment]
great!
