### ISSUE TITLE
return value not initialized

### ISSUE THREAD

**Issue by ajax2leet** [joshspeagle/dynesty#49]
First of all, thanks for this awesome tool!

However, there is a small bug in version 0.8.0:
https://github.com/joshspeagle/dynesty/blob/cd655fd7fa4cb854809523bd920b63ffa1a44396/dynesty/bounding.py#L1145

The return value of the function `make_eigvals_positive` is not initialized of the if statement fails.

**Comment by joshspeagle** [comment]
Good catch. I'll push an update to fix that bug along with the update to #48 soon.
