### ISSUE TITLE
Issue merging runs

### ISSUE THREAD

**Issue by dadams42** [joshspeagle/dynesty#491]
** Dynesty version **
2.1.4

**Describe the bug**
Independent runs can't be merged using utils.merge_runs() from dynesty.  I did not experience this issue in previous versions. 

**Setup**
I am running the following dynesty setup:
A sample code in Jupyter Notebook returning the error is attached, it can be quickly run if one has some independent runs. Some runs do appear to merge successfully, most of the time not. Both are converged, use same likelihood, priortransforms etc. 

** Dynesty output **
Returns an error saying "operands could not broadcast together".

**Bug**
The merging process fails and the independent runs are not combined. 
![non_merge](https://github.com/user-attachments/assets/f4a2f1cc-fccf-4e34-bc2c-04e5bc73d603)

**Comment by segasai** [comment]
Hi,

Could you please try the master branch ? 
I've fixed one merging issue here:
https://github.com/joshspeagle/dynesty/pull/482
but I haven't made a new release yet.
If that fixes it, than I'll try to cut the release now with all the fixes.

**Comment by segasai** [comment]
I've created the 2.1.5 release now with the fixes in.
