### ISSUE TITLE
Only import Matplotlib if necessary

### ISSUE THREAD

**Issue by pacargile** [joshspeagle/dynesty#54]
When using dynesty on large parallel cpu clusters, matplotlib is many times not needed and sometimes not available resulting in a ImportError. Therefore, it would be better/more efficient if dynesty only imported matplotlib if the user wanted to use the visualization submodule.

**Comment by joshspeagle** [comment]
Good point. I can change `__init__` to by default *not* import `plotting`. Are there any other instances where `matplotlib` is imported within the code?

**Comment by pacargile** [comment]
I don't think so, or at least I have not come across them yet.

**Comment by joshspeagle** [comment]
Resolved in 5927d4d882cdee6ac9968620f4f487e3da98c9eb.

**Comment by pacargile** [comment]
It still seems to be importing Matplotlib, I think it is due to the fact that you are using "from .dynesty import *", is this importing "plotting" even though it is not explicitly defined?

**Comment by joshspeagle** [comment]
Do you have a copy of the error where/when this import occurs?

**Comment by pacargile** [comment]
Sorry, I was still on version 0.8.2. I pulled the repo to 0.8.3 and the issue with matplotlib has gone away.
