### ISSUE TITLE
sampler.results dictionary missing information

### ISSUE THREAD

**Issue by pacargile** [joshspeagle/dynesty#56]
Just updated Dynesty and now the sampler.results object does not report the information "h" parameter in the dictionary.

**Comment by joshspeagle** [comment]
I believe I changed the name to "information". Is that present?

**Comment by pacargile** [comment]
Ah yes, "information" is there. Thank you.

Btw, it might be good to list all of the keys and a short description in the results dictionary on the API doc page:

https://dynesty.readthedocs.io/en/latest/api.html#module-dynesty.results

**Comment by joshspeagle** [comment]
Yea, that's probably a good idea. I'll add it to the docs when I next update the code.
