### ISSUE TITLE
Listing dynesty on PyPi (so can be pip installed)

### ISSUE THREAD

**Issue by bacook17** [joshspeagle/dynesty#65]
I'm working on packaging my code into something that can be pip installed, but having any dependencies that aren't listed on PyPi is tricky and somewhat fragile (the only workaround is currently deprecated and due to be removed in the future).

Sometime in the future, do you expect to list dynesty on PyPi?

**Comment by joshspeagle** [comment]
Yea, I'm hoping to add it in once I finish developing/implementing the list of final features mentioned in the remaining open issues.
