### ISSUE TITLE
Default `queue_size` should be `pool.size`, not 1

### ISSUE THREAD

**Issue by guillochon** [joshspeagle/dynesty#79]
Just realized why my parallel runs weren't as fast: I wasn't passing `queue_size` when initializing the sampler. However, it does seem to me when a `pool` is passed to the initialization that the default behavior should be to use `pool.size` instead of 1. Is it possible to change this behavior?

**Comment by joshspeagle** [comment]
Yes, this seems like a pretty straightforward change. I'll try and push it this weekend.
