### ISSUE TITLE
Add CI to dynesty

### ISSUE THREAD

**Issue by guillochon** [joshspeagle/dynesty#81]
Dynesty should have a battery of tests that run after changes (i.e. continous integration) that ensure that commits don't break anything. The simplest way is probably via travis. Some basic info on how to do so for a Python project is available [here](https://docs.travis-ci.com/user/languages/python/).

**Comment by joshspeagle** [comment]
Definitely agree. I'll try and add this in before I do any more large-scale edits to avoid introducing any unintended bugs.

**Comment by joshspeagle** [comment]
Resolved in eb7c48082048be0b23a4578c1078f9ccdbcde2eb
