### ISSUE TITLE
stopping criteria check

### ISSUE THREAD

**Issue by joshspeagle** [joshspeagle/dynesty#92]
I derived some basic results for the stopping criteria as part of a related project. I should confirm that the basic findings check out in dynesty and adjust the stopping criteria accordingly. This needs to be done before the initial package release since the stopping criteria is a huge selling point.

**Comment by joshspeagle** [comment]
This seems to be alright, so I'm closing this.

Note: I should include the comparison to MCMC methods in the paper. Also reference the discussion I had with @aimalz concerning what metrics we would *ideally* want.

**Comment by aimalz** [comment]
Indeed, let me know if you'd like a hand implementing or writing about the alternative convergence criterion we discussed.
